Chore: e2e tests on gmcq component (Issue/177)
adaptlearning/adapt-contrib-gmcq pull request #178
Opened 2024-03-26 19:43 UTC by lemmyadams

Addresses #177

2024-03-26 19:57 UTC, lemmyadams commented
@cahirodoherty-learningpool on this test and the other questions I test for the buttons appearing as expected, for the submit and show feedback. 
The code is:
function testQuestionButtons(buttonsObject = {btn__action: 'Submit', btn__feedback: 'Show feedback'}) {
  Object.keys(buttonsObject).forEach((key) => {
    cy.get(`.${key}`).should('contain', buttonsObject[key])
  })
}
Just getting your thoughts before I raise an issue on the framework

2024-03-27 08:26 UTC, cahirodoherty-learningpool commented
> @cahirodoherty-learningpool on this test and the other questions I test for the buttons appearing as expected, for the submit and show feedback. The code is:
> 
> ```
> function testQuestionButtons(buttonsObject = {btn__action: 'Submit', btn__feedback: 'Show feedback'}) {
>   Object.keys(buttonsObject).forEach((key) => {
>     cy.get('.${key}').should('contain', buttonsObject[key])
>   })
> }
> ```
> 
> Just getting your thoughts before I raise an issue on the framework

This looks okay on first inspection anyway. As long as the buttonsObject is passed as a param for each plugin that uses this helper 👍

2024-03-27 11:01 UTC, lemmyadams commented
Relies on https://github.com/adaptlearning/adapt_framework/pull/3533

2024-03-28 09:43 UTC, cahirodoherty-learningpool approved these changes
👀

2024-03-28 12:22 UTC, ethan-lp approved these changes

2024-04-11 13:38 UTC, oliverfoster requested changes

2024-04-11 13:38 UTC, oliverfoster commented on test/e2e/gmcq.cy.js
> +        cy.testContainsOrNotExists('.gmcq-item__text', item.text);
Please check all of the tested properties for the `compile` helper. That's where the json data is processed as a handlebars template and can produce html.

https://github.com/adaptlearning/adapt-contrib-gmcq/blob/eeadd8f17e1752763a62f3b014d5234380e6b1d0/templates/gmcq.jsx#L127

2024-04-11 14:26 UTC, oliverfoster approved these changes

2024-04-11 14:26 UTC, merged